In [2]:
import numpy as np

In [7]:
#create a array size of 10, filled with zeros
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
# array starting from 10 to 49
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [20]:
# matrix 2x2, filled with ones
np.ones([2,2], dtype = int)

array([[1, 1],
       [1, 1]])

In [24]:
#Create a numpy matrix of 3*2 float numbers, filled with ones
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
#Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones

X = np.arange(10,20,2)
print(X)
np.ones_like(X)

[10 12 14 16 18]


array([1, 1, 1, 1, 1])

In [57]:
#Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

X = np.array([[1,2,3],[1,2,3]])
print(X)
np.zeros_like(X)

[[1 2 3]
 [1 2 3]]


array([[0, 0, 0],
       [0, 0, 0]])

In [83]:
# Create a numpy matrix of 4*4 integers, filled with fives.¶

x = np.ones([4,4], dtype= int)
print(x)
x*5

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [92]:
#Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.
X = np.array([[2,3], [6,2]])
#print(X)
Y = np.ones_like(X)*7
print(Y)

[[7 7]
 [7 7]]


In [99]:
# Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.¶
#np.array([[0,1,1],[1,1,0]])
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [121]:
 #Create a numpy array, filled with 3 random integer values between 1 and 10
np.random.randint(10,size =3) 

array([9, 3, 2])

In [ ]:
# Given the X python list convert it to an Y numpy array¶
X = [1,2,3,4]
print(type(X))
Y = np.array(X)
print(Y)

In [21]:
a = np.arange(5)
a+20
print(a)



[0 1 2 3 4]


In [70]:

X = np.array([33,55,33,5,56])

mask = (X == 33) | (X ==5)


X[mask]

array([33, 33,  5])

In [77]:
X = np.array([33,55,33,5,56])
X.mean()
#mask = X> X.mean()

#X[mask]

array([55, 56])

In [5]:
np.random.random(size=3)


array([0.38330954, 0.78578042, 0.33010755])

In [12]:
np.random.normal(size=3)

array([1.18641106, 0.95358444, 0.4281912 ])

In [15]:
np.random.rand(2, 4)


array([[0.69178917, 0.6205326 , 0.02205505, 0.26850535],
       [0.17833464, 0.41277085, 0.76267995, 0.21781965]])

In [16]:
np.arange(10).reshape(2, 5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])